### ISSUE TITLE
Question: is the loc package on stackage lts ?

### ISSUE THREAD

**Issue by clojj** [chris-martin/loc#4]
I can't find it on stackage..

**Comment by chris-martin** [comment]
I haven't yet, I've been meaning to. Thanks, I'll get on that.

**Comment by clojj** [comment]
my current project (depending on loc) is at lts-12.20.. 
I'm mentioning that becaus here
https://github.com/chris-martin/loc/blob/master/stack-lts-12.yaml
it's still on 12.19

**Comment by chris-martin** [comment]
I submitted it to Stackage a couple days ago, but it hasn't been merged yet. I'm not sure why not.

https://github.com/commercialhaskell/stackage/pull/4176

**Comment by clojj** [comment]
it is merged now
from my experience, they first merge to 'nightly'... meaning it should be included in tomorrows nightly resolver
For lts-12 an issue should be created like so (it was recently done for rosezipper package) :
https://github.com/commercialhaskell/lts-haskell/issues/184
